Month 7/step 1
forfrontskill/react-burger pull request #1
Opened 2022-09-08 16:31 UTC by forfrontskill

2022-09-08 18:33 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа. Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

**Вы молодцы!** 🔥

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

**Но есть несколько замечаний, которые нужно исправить:**
- В директории `components` должен быть компонент App. Компонент `App`, как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;
- Для компонентов с пропсами требуется описать propTypes;
- В шапке сайте, должны быть ссылки. Более подробно см. комментарий в коде;

**Сделает код лучше:**

- Для элемента `img` следует указывать атрибут alt. Этот атрибут дает понять пользователям, что изображено на этой картинке.

**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-08 18:33 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +                {list.map((burgerElement, index,array) => {
**Можно лучше:** Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален. В данном случае, никак не используется переменная array.

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    }
**Можно лучше:** Лучше в компоненте до вывода отфильтровать список ингредиентов от булок, и вывести булки отдельно; Также вынести эти 2 условия в переменные, а после сделать из этого 1 проверку.

Например
```js 

const a = 'top'

const isTop = a === 'top';
const isBottom = a === 'bottom';

if(isTop || isBottom) {
  // ... что-то делаем
}

```
Также чтобы еще больше сократить код, значение в пропсе type можно сделать через тернарный оператор. Подробнее: https://learn.javascript.ru/ifelse#uslovnyy-operator

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/burger-constructor-element/burger-constructor-element.jsx
> +const BurgerConstructorElement = ({text,price,thumbnail,isLocked=true,type}) => {
**Надо исправить**: для этого компонента нужно описать PropTypes

2022-09-08 18:33 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +const BurgerConstructor = ({ price = 12 }) => {
**Надо исправить**: для этого компонента также нужно описать PropTypes

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/burger-ingredient/burger-ingredient.jsx
> +const BurgerIngredient = ({image, price, count, name}) => {
**Надо исправить**: для этого компонента также нужно описать PropTypes

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/burger-ingredients-group/burger-ingredients-group.jsx
> +const BurgerIngredientsGroup = ({title,list,refProp}) => {
**Надо исправить**: для этого компонента также нужно описать PropTypes

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/content/content.jsx
> +const Content = ({children}) => {
**Надо исправить**: для этого компонента также нужно описать PropTypes

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/menu-button/menu-button.jsx
> +const MenuButton = ({icon, text='', type='inactive', onClick=()=>{}}) => {
**Надо исправить**: для этого компонента также нужно описать PropTypes

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/menu-button/menu-button.jsx
> +    )
**Надо исправить:** В шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в 3 спринте, этого делать сейчас не нужно. Также элементы в шапке должны быть ссылками, а в будущем вы будете использовать компонент Link.

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/menu-button/menu-button.module.css
> +    margin: 0 8px 0 0;
**Можно лучше:** Здесь и далее. У свойства margin есть отдельное свойство для указания отступов сверху, снизу, справа, слева. Это margin-top,  margin-bottom, margin-right, margin-left, соответственно.

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/title/title.jsx
> +const Title = ({text=''}) => {
Надо исправить: для этого компонента также нужно описать PropTypes

2022-09-08 18:33 UTC, ArslanDev666 commented on src/index.tsx
> +    </Content>
Надо исправить: Лучше вынести эти компоненты в компонент App. Т.к компонент `App`, как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов.

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/utils/utils.jsx
> +    }
**Можно лучше:** Стоит еще раз проверить, нужно ли это условие, т.к у в задании нигде не было сказано о том, что у ингредиента не будет поля `type`.

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                        key={burgerElement._id}
**Отлично**: Очень хорошо что вы указываете key.

2022-09-08 18:33 UTC, ArslanDev666 commented on src/components/burger-ingredients-group/burger-ingredients-group.jsx
> +                {list.map((ingredient) => <BurgerIngredient key={ingredient._id} {...ingredient}/>)}
**Отлично**: Очень хорошо что вы указываете key.

2022-09-08 22:33 UTC, forfrontskill commented on src/components/burger-constructor/burger-constructor.jsx
> +                {list.map((burgerElement, index,array) => {
fix

2022-09-08 22:37 UTC, forfrontskill commented on src/components/burger-constructor/burger-constructor.jsx
> +                        key={burgerElement._id}
👍

2022-09-08 22:37 UTC, forfrontskill commented on src/components/burger-ingredients-group/burger-ingredients-group.jsx
> +                {list.map((ingredient) => <BurgerIngredient key={ingredient._id} {...ingredient}/>)}
👍

2022-09-08 22:53 UTC, forfrontskill commented on src/components/burger-constructor-element/burger-constructor-element.jsx
> +const BurgerConstructorElement = ({text,price,thumbnail,isLocked=true,type}) => {
fix

2022-09-08 22:54 UTC, forfrontskill commented on src/components/burger-constructor/burger-constructor.jsx
> +const BurgerConstructor = ({ price = 12 }) => {
fix

2022-09-08 22:58 UTC, forfrontskill commented on src/components/burger-ingredient/burger-ingredient.jsx
> +const BurgerIngredient = ({image, price, count, name}) => {
fix

2022-09-08 23:00 UTC, forfrontskill commented on src/components/title/title.jsx
> +const Title = ({text=''}) => {
fix

2022-09-08 23:05 UTC, forfrontskill commented on src/components/utils/utils.jsx
> +    }
Тут добавление нового свойства в аккумулирующий объект, если его нет.

2022-09-08 23:14 UTC, forfrontskill commented on src/components/burger-ingredients-group/burger-ingredients-group.jsx
> +const BurgerIngredientsGroup = ({title,list,refProp}) => {
fix

2022-09-08 23:16 UTC, forfrontskill commented on src/components/content/content.jsx
> +const Content = ({children}) => {
fix

2022-09-08 23:19 UTC, forfrontskill commented on src/components/menu-button/menu-button.jsx
> +const MenuButton = ({icon, text='', type='inactive', onClick=()=>{}}) => {
fix

2022-09-09 07:00 UTC, ArslanDev666 commented on src/components/utils/utils.jsx
> +    }
А да, точно, вы правы)) в таком случае тут все в порядке!)

2022-09-09 22:55 UTC, forfrontskill commented on src/components/menu-button/menu-button.jsx
> +    )
fixed

2022-09-09 23:04 UTC, forfrontskill commented on src/index.tsx
> +    </Content>
fix

2022-09-17 17:34 UTC, merged