Month 7/step 2
forfrontskill/react-burger pull request #2
Opened 2022-09-13 17:31 UTC by forfrontskill

2022-09-14 09:23 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

На будущие, лучше вести работу в 1 PR.

Все замечания были из прошлого ревью были исправлены.

**Но есть несколько новых замечаний:**

- Необходимо добавить проверку ответа сервера - res.ok, и другие мелкие изменения;

- Если в качестве пропсов передается объект или массив объектов, то в propTypes должна быть описана структура этого объекта.

- Если параметры у компонента обязательные, то нет необходимости указывать им default значение;

- Иконка с точками должна быть только у начинки бургера, у булок её быть не должно т.к. их нельзя перетаскивать;

- Скролл должен присутствовать только у начинки бургера. Сами булки не должны скроллится;

- В описании propTypes у компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается. 


**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +const baseUrl = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить**
Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`. Также имена констант принято записывать в стиле UPPER_CASE.

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +    }, [])
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше  разместить их в отдельном файле  `utils/burger-api.js`

Например:

```

const NORMA_API = `https://norma.nomoreparties.space/api`;

export function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(checkReponse )
}

export function sendOrder(data) {
   return fetch(`${NORMA_API}/orders`)
    .then(checkReponse )
}

```

, а не описывать запросы в самом компоненте

----

**Надо исправить**

Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +                setFetching(true);
**Можно лучше**
вызывать скрытие индикатора загрузки слудеует в блоке `finally`, а не дублировать в `then` или `catch`
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +            })
**Можно лучше**
хорошо, что обрабатывается ошибка запроса к api, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +import ModalOverlay from "../modal-overlay/modal-overlay";
**Можно лучше:** Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +                    }
Можно лучше: говорил [ранее](https://github.com/forfrontskill/react-burger/pull/1)

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +}
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Также, тут лучше указывать не просто `PropTypes.array`, а `PropTypes.arrayOf`. и описать структуру ингредиента.
Структуру ингредиента, лучше вынести в отдельный файл, т.к во многих местах она будет повторяться. 


Проверьте во всем проекте.

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/burger-ingredient/burger-ingredient.jsx
> +    ingredient: PropTypes.object.isRequired,
**Надо  исправить:** Вместо `PropTypes.object` лучше использовать `PropTypes.shape`. Как и ранее говорилось: Структуру ингредиента, лучше вынести в отдельный файл, т.к во многих местах она будет повторяться.

2022-09-14 09:23 UTC, ArslanMustafin commented on src/components/burger-ingredient/burger-ingredient.jsx
> +const BurgerIngredient = ({ingredient, onClick=()=>{}}) => {
**Надо исправить:** Здесь и в других файлах. Если onClick или другие параметры обязательные, то нет необходимости указывать default значение.

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    }, []);
**Можно лучше:** Можно задать каждому заголовку соответствующий id  и вызывать scrollIntoView, при клике на Tab
Например:
```js
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };
```

где заголовкам разделов заданы соответствующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView.

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                </Tab>
**Надо исправить:** `onClick` по умолчанию передает туда значение из параметра value, поэтому лучше использовать функцию без аргументов.

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const mainList = ingredientFilter(ingredients);
**Можно лучше**
используйте useMemo, что бы фильтрация ингредиентов не вызывалась при каждом ренедере, например:
```
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
.....
```

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/ingredient-details/ingredient-details.jsx
> +const IngredientDetails = ({ isOpen=false, onClose=()=>{}, ingredient }) => {
**Можно лучше:**  Если isOpen не будет передан, то он по умолчанию будет `undefined`, а `undefined` всегда `false`.

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/menu-button/menu-button.jsx
> +    const textType = type === 'inactive' ? 'text_color_inactive' : 'text_color_primary';
**Надо исправить**: в шапке активный пункт меню будет определяться с помощью роутинга, это будет реализовано в будущем, не нужно сейчас это делать через стейт.

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.jsx
> +    return isOpen ? ReactDOM.createPortal(modal, modalRoot) : <></>
**Надо исправить**

не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
```

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.module.css
> +        /* transition: visibility 0s,opacity 0.3s linear; */
**Можно лучше:** Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/utils/utils.jsx
> +},{})
**Надо исправить**: т.к в файле utils не содержится jsx элементов, то лучше поменять расширение на `.js`, а также вынести файл/папку за пределы папки `components`

2022-09-14 09:23 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.jsx
> +    }, [])
**Можно лучше**: Функцию `eventEscKey` можно создать в самом `useEffect`, а также в качестве зависимостей в `useEffect` передать функцию `onClose`. В этом случае функция `eventEscKey`, не будет создаваться заново при каждом ререндере компонента. Подробнее про useEffect: https://ru.reactjs.org/docs/hooks-reference.html#useeffect

2022-09-15 17:07 UTC, forfrontskill commented on src/components/app/app.jsx
> +const baseUrl = 'https://norma.nomoreparties.space/api/ingredients';
fix

2022-09-15 17:10 UTC, forfrontskill commented on src/components/app/app.jsx
> +import ModalOverlay from "../modal-overlay/modal-overlay";
fix

2022-09-15 17:32 UTC, forfrontskill commented on src/components/app/app.jsx
> +    }, [])
fix. 
Отличное пояснение 👍

2022-09-15 17:36 UTC, forfrontskill commented on src/components/utils/utils.jsx
> +},{})
fix

2022-09-15 17:37 UTC, forfrontskill commented on src/components/app/app.jsx
> +                setFetching(true);
fix

2022-09-15 18:03 UTC, forfrontskill commented on src/components/app/app.jsx
> +            })
fix

2022-09-15 18:59 UTC, forfrontskill commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                </Tab>
fix

2022-09-15 19:02 UTC, forfrontskill commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const mainList = ingredientFilter(ingredients);
fix

2022-09-15 19:05 UTC, forfrontskill commented on src/components/modal-overlay/modal-overlay.module.css
> +        /* transition: visibility 0s,opacity 0.3s linear; */
fix

2022-09-15 19:12 UTC, forfrontskill commented on src/components/menu-button/menu-button.jsx
> +    const textType = type === 'inactive' ? 'text_color_inactive' : 'text_color_primary';
плохо понимаю замечание... это просто определение состояния компонента кнопки меню в зависимости от type. Сейчас активная кнопка прибита гвоздями с типом type='active'

2022-09-15 19:16 UTC, forfrontskill commented on src/components/modal-overlay/modal-overlay.jsx
> +    return isOpen ? ReactDOM.createPortal(modal, modalRoot) : <></>
fix

2022-09-15 19:20 UTC, forfrontskill commented on src/components/ingredient-details/ingredient-details.jsx
> +const IngredientDetails = ({ isOpen=false, onClose=()=>{}, ingredient }) => {
fix

2022-09-15 19:40 UTC, forfrontskill commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    }, []);
fix

2022-09-15 20:37 UTC, forfrontskill commented on src/components/burger-constructor/burger-constructor.jsx
> +}
fix

2022-09-15 20:37 UTC, forfrontskill commented on src/components/burger-ingredient/burger-ingredient.jsx
> +    ingredient: PropTypes.object.isRequired,
fix

2022-09-15 20:37 UTC, forfrontskill commented on src/components/burger-ingredient/burger-ingredient.jsx
> +const BurgerIngredient = ({ingredient, onClick=()=>{}}) => {
fix

2022-09-15 20:47 UTC, forfrontskill commented on src/components/modal-overlay/modal-overlay.jsx
> +    }, [])
fix

2022-09-15 21:13 UTC, forfrontskill commented on src/components/burger-constructor/burger-constructor.jsx
> +                    }
fix

2022-09-16 18:10 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    const top = buns[1];
**Можно лучше:** у вас почти идеальное решение🔥, но можно еще лучше, вот так например:
```js 
  const bun = useMemo(() => ingredients.find((ingredient) => ingredient.type === "bun"), [ingredients]);
```
Нам незачем использовать 2 переменные, т.к булка у нас всегда будет одна.

2022-09-16 18:10 UTC, ArslanDev666 commented on src/components/burger-ingredient/burger-ingredient.jsx
> +    ingredient: IngredientType,
**Можно лучше:** Лучше дополнительно указать `isRequired`. Нотация `.isRequired` расширяет валидатор и делает свойство обязательным.

2022-09-16 18:10 UTC, ArslanDev666 commented on src/components/menu-button/menu-button.jsx
> +    const textType = type === 'inactive' ? 'text_color_inactive' : 'text_color_primary';
Я пересмотрел этот момент, вроде не сложно будет приспособить это для роутинга, Даже, думаю так будет лучше, Вы молодец 🔥 Вы достаточно грамотно всё сделали.

2022-09-16 18:32 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Почти все замечания из прошлого ревью были исправлены.

**есть 1 старое замечание:**

- Скролл должен присутствовать только у начинки бургера. Сами булки не должны скролится; Приложил скрин, как это может выглядеть.

![image](https://user-images.githubusercontent.com/70164458/190707400-a1036910-4e20-4238-96f9-6aa0f6a63675.png)


**А также есть несколько новых замечаний:**

- По чек-листу у вас должен быть компонент Modal и ModalOverlay. 
В вашей ситуации достаточно переименовать компонент modal-overlay в modal. 
А также создать компонент ModalOverlay.

т.е в вашем случае jsx-разметка компонента modal будет вот такая:
```js
<>
  <div className={style.modal}>...</div>
  <ModalOverlay onClose={onClose} />
</>
```
а компонент ModalOverlay будет всего лишь 1 дивом с абсолютным позиционированием. Не забудьте про z-index.

- Модальные окна должны закрываться также при клике на ModalOverlay;

**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-16 20:59 UTC, forfrontskill commented on src/components/burger-ingredient/burger-ingredient.jsx
> +    ingredient: IngredientType,
fix

2022-09-16 21:18 UTC, forfrontskill commented on src/components/burger-constructor/burger-constructor.jsx
> +    const top = buns[1];
fix

2022-09-16 21:21 UTC, forfrontskill commented
Спасибо, понял теперь, что именно требовалось от скролла....

2022-09-17 04:39 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Все замечания из прошлого ревью были исправлены.🔥

**Описал 1 новое замечание, подробнее об этом в коде.**

2022-09-17 04:39 UTC, ArslanDev666 commented on src/components/modal-overlay/modal-overlay.jsx
> +    }
**Надо исправить:** Решение очень интересное, вы хорошо постарались. 
Но можно этот компонент сделать немного проще.
Например: 
- Убрать лишние функции, и не передавать `children`: 
```js
const ModalOverlay = ({ onClose }) => {
  return <div className={styles.overlay} onClick={onClose} />;
};
```
Тогда компонент `Modal` будет выглядеть таким образом.

```js 
const Modal = ({ title, onClose, children }) => {

    // ...

    return (
        <>
            <div className={style.Container}>
               {/* ... */}
            </div>
            <ModalOverlay onClick={onClose} />
        </>
    )
}

```
И если что-то будет не понятно, то пишите, попробую объяснить. 
Также приложил похожую реализацию.
https://codepen.io/arslandev666/pen/VwxprRb?editors=1011

2022-09-17 15:14 UTC, forfrontskill commented on src/components/modal-overlay/modal-overlay.jsx
> +    }
Спасибо! Хорошое объяснение. Благодаря примеру все понятно, все бы так делали 👍 
Действительно, компонент так выглядит проще и не требуется приделывать костыли обработки кликов.

2022-09-17 16:12 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания были исправлены!🔥

**Работа была не простая, но вы справились. Вы молодец!**

2022-09-17 17:34 UTC, merged